modules/pipeline_lua/module/src/allocator.c
modules/pipeline_lua/module/src/base.lua
modules/pipeline_lua/module/src/binary.lua
modules/pipeline_lua/module/src/builtin_lua.c
modules/pipeline_lua/module/src/pipeline_lua.c
modules/pipeline_lua/module/src/pipeline_lua_int.h

These changes implement the extensions defined in LOXI by https://github.com/floodlight/loxigen/pull/374.
My original usecase for these messages was OFTest. For testing APIs that aren't tied to an event like an upcall it's much simpler to activate the testcase using this message rather than sending some specially crafted packet or gentable entry. I now think it's also useful for querying small amounts of data from the switch or sending non-configuration commands like "reset counter".
The binary reader/writer and bump allocator will be used for tables and packet-ins in the future.

Implement of_bsn_lua_command_request message

---

modules/OVSDriver/module/src/dump.c
modules/OVSDriver/module/src/kflow.c
modules/OVSDriver/module/src/ovs_driver.c
modules/OVSDriver/module/src/ovs_driver_int.h
modules/OVSDriver/module/src/pktout.c
modules/OVSDriver/module/src/translate_match.c
modules/OVSDriver/module/src/upcall.c
modules/pipeline/module/inc/pipeline/pipeline.h
modules/pipeline/module/src/pipeline.c
modules/pipeline_lua/module/src/pipeline_lua.c
modules/pipeline_reflect/module/src/pipeline_reflect.c
modules/pipeline_standard/module/src/pipeline_standard.c

Pipeline implementations are given a mask to fill in when processing a
flow. For every key bit it used when processing a flow, the pipeline must
set the corresponding mask bit to one. This mask is sent to the kernel when
inserting a kflow. Any future packets that agree with the kflow key where
the mask bit is one will hit, reducing the number of kflows that need to be
installed.
This change does not yet generate useful masks from the built-in pipelines.

megaflow infrastructure

---

modules/OVSDriver/module/src/util.c

OVSDriver: fix a leak of netlink sockets when nl_connect fails

---

.abat-automerge
Makefile
build/build-rhel-packages-inner.sh
build/build-rhel-packages.sh
docker/centos7/Dockerfile
rhel/ivs-7.0.spec

I created a bigswitch/ivs-builder Docker repo with one tag for
"centos7". This Docker image has all the build dependencies for IVS.
When you run the build-rhel-packages.sh script, it will download this
image, copy the IVS source code into it, run rpmbuild, and extract the
resulting RPMs. After the image has been been downloaded (which only
happens the first time) the build completes in about a minute.

build centos7 RPMs using Docker

---

modules/OVSDriver/module/src/ovs_driver_int.h
modules/OVSDriver/module/src/upcall.c
modules/shared_debug_counter/.gitignore
modules/shared_debug_counter/module/inc/shared_debug_counter/shared_debug_counter.h
modules/shared_debug_counter/module/make.mk
modules/shared_debug_counter/module/src/link.ld
modules/shared_debug_counter/module/src/make.mk
modules/shared_debug_counter/module/src/shared_debug_counter.c
targets/ivs/Makefile
targets/ivs/main.c

This module is a wrapper around debug counters which places them in shared
memory. This is necessary for debug counter updates from upcall processes to be
persistent and visible to the controller.
Also adds a few shared debug counters to upcall.c. We'll add more in the future.

shared debug counters

---

modules/OVSDriver/module/src/vport.c

This hasn't been required since we moved to a multi-process model.

OVSDriver: remove unnecessary memory barrier

---

modules/OVSDriver/module/src/vport.c

Rarely, an uplink netdev can disappear and come back. This can be caused by 
reloading the driver's kernel module or hotplugging the hardware. This change 
watches for an uplink to reappear and adds it back to the datapath.

OVSDriver: automatically reconnect uplinks to the datapath

---

modules/OVSDriver/module/src/ovs_driver.c
modules/OVSDriver/module/src/ovs_driver_int.h
modules/OVSDriver/module/src/pktin.c
modules/OVSDriver/module/src/pktin_socket.c
modules/OVSDriver/module/src/pktout.c
modules/ivs/module/inc/ivs/ivs.h
modules/pipeline_standard/module/src/action.c
modules/pipeline_standard/module/src/action.h
modules/pipeline_standard/module/src/pipeline_standard.c

Reviewer: @rlane 
Commit Summary: Allow pipelines to register netlink sockets to receive pktin's. Pipeline will set the callback to be associated with each socket which will be invoked when a packet is recv'd on that socket. 
Pipeline will also set the ratelimiter associated with that socket.
Todo: Add timer to pause/resume the socket on ratelimiter overflow.

add capability for the pipeline to create/destroy pktin netlink sockets

---

modules/OVSDriver/module/src/barrier.c

allow flows to be revalidated without having a cxn_id

---

modules/OVSDriver/module/src/ovs_driver.c

It's undefined behavior to left shift a value by more than its width. The 
mac[x] values are uint8_t, not uint32_t as the code assumed.

OVSDriver: fix shifting when constructing DPID from MAC

---

modules/ivs/module/inc/ivs/ivs.h

The Ubuntu 14.04 kernel has a bug which prevents installing flows which match 
on ND fields. The implementation in IVS was also buggy because it was in a 
union with the icmpv6 key.
Given these bugs, it's better to remove the ability to match on ND fields and 
allow those flows to be installed in the kernel.

OVSDriver: remove ICMPv6 ND from key

---

modules/OVSDriver/module/src/ovs_driver_int.h
modules/OVSDriver/module/src/uplink.c
modules/OVSDriver/module/src/vport.c
modules/ivs/module/inc/ivs/ivs.h
modules/pipeline/module/src/pipeline.c

The previous algorithm for picking an uplink iterated through all ports to
find the first live one with the uplink bit set. This was more expensive than 
necessary, but the main problem is that IFF_RUNNING doesn't mean that the 
switch on the other side is ready to forward packets. We don't want to move
our inband OpenFlow connections from a working uplink to a potentially
not-working one.
This change runs the uplink selection algorithm on port events instead of for 
every packet. It will try to keep the same uplink as long as it's still live.

OVSDriver: sticky uplinks

---

modules/OVSDriver/module/src/multicast.c
modules/OVSDriver/module/src/ovs_driver_int.h
modules/OVSDriver/module/src/vport.c

The kernel used to give us the MAC in the vport added notification, and the old
code was a hack to emulate that. The new code is cleaner and faster.

cleanup getting the vport MAC address

---

modules/Manifest.mk
modules/OVSDriver/module/src/upcall.c
modules/action/module/src/action.c
modules/packet_trace/.gitignore
modules/packet_trace/module/inc/packet_trace/packet_trace.h
modules/packet_trace/module/make.mk
modules/packet_trace/module/src/make.mk
modules/packet_trace/module/src/packet_trace.c
modules/pipeline/module/src/pipeline.c
modules/pipeline_standard/module/src/action.c
modules/pipeline_standard/module/src/cfr.c
modules/pipeline_standard/module/src/cfr.h
modules/pipeline_standard/module/src/pipeline_standard.c
targets/ivs-ctl/ivs-ctl.8
targets/ivs-ctl/main.c
targets/ivs/Makefile
targets/ivs/main.c

This pull request adds a new "trace" command to ivs-ctl. With this command you can watch the forwarding decisions being made in real time. This is extremely useful for debugging issues where packets aren't being forwarded as expected.
This code is designed to have minimal performance impact when no trace clients are connected or when no filters match a given packet. It should be easy to add new types of filters besides just port number.
Usage:
ivs-ctl trace port 6 # Show all packets from port 6
ivs-ctl trace # Show all packets

Packet trace

---

modules/packet_trace/module/src/packet_trace.c

We're passing a va_list, so we have to use aim_log_vcommon.

packet_trace: fix logging bug

---

build/build-debian-packages-inner.sh
build/build-debian-packages.sh
build/build-rhel-packages-inner.sh
build/build-rhel-packages.sh
docker/centos7/Dockerfile
docker/ubuntu14.04/Dockerfile

ccache needs a persistent cache directory to be useful. We mount
/tmp/ivs.ccache into the containers as .ccache.

use ccache to build packages faster

---

modules/OVSDriver/module/src/kflow.c
modules/OVSDriver/module/src/ovs_driver_int.h

An upcall thread might request multiple overlapping kflows. This is 
particularly true for inband, where the kflow mask only includes in_port. 
Before megaflows, we handled this case with a hash table keyed on the kflow 
key. This isn't sufficient anymore because different keys can match the same 
megaflow. The fix is to switch from a hashtable to the TCAM datastructure we 
use in the forwarding pipeline.

OVSDriver: ignore duplicate megaflow requests

---

modules/pipeline_lua/module/src/table.c
oftests/l2switch.x
oftests/l2switch_xdr.py
oftests/lua/l2switch.lua
oftests/lua/l2switch_xdr.lua
oftests/lua_l2switch.py

This is a prototype for reducing redundancy in OpenFlow tables. The controller
can program a small number of abstract tables, and the Lua code can translate
them into a lower level, more efficient set of tables used for forwarding.

use a single "endpoint" table in l2switch

---

modules/OVSDriver/module/src/kflow.c
modules/OVSDriver/module/src/pktin_socket.c
modules/OVSDriver/module/src/upcall.c

These counters are useful for debugging drops of packet-ins, kflow requests, 
and upcalls.

OVSDriver: add more performance debug counters

---

modules/OVSDriver/module/src/vport.c
modules/ivs/module/inc/ivs/ivs.h

This is useful in the implementation of select groups in the pipeline.

OVSDriver: add API to get link state

---

targets/ivs/main.c

The port numbers assigned at startup could collide with port numbers inherited 
from the datapath.

ivs: make kernel assign initial port numbers

---

modules/OVSDriver/module/src/ovs_driver_int.h
modules/OVSDriver/module/src/util.c
modules/OVSDriver/module/src/vport.c

If LRO is enabled I see large (but not over MTU) packets being lost after 
missing in the kernel flowtable. They fail a skb->len <= mss check in 
tcp_gso_segment. It's not clear why ixgbe marks these packets as needing GSO. 
Disabling LRO works around the issue, and I found that OVS is doing the same 
thing.

OVSDriver: disable LRO on port add

---

modules/OVSDriver/module/inc/OVSDriver/ovsdriver.h
modules/OVSDriver/module/src/hitless.c
modules/OVSDriver/module/src/kflow.c
modules/OVSDriver/module/src/ovs_driver.c
modules/OVSDriver/module/src/ovs_driver_int.h
targets/ivs/ivs.8
targets/ivs/main.c
tests/hitless.py

The goal of these changes is to reduce the interval after restarting IVS
during which packets from long-lived flows are lost. See the big comment in
hitless.c for implementation details.
This assumes a proactive OpenFlow controller which sends the bsn_takeover
experimenter message after it has pushed all table entries. The barrier
message might have been used instead, but since OpenFlow uses the same
barrier message for both message ordering and dataplane commit it's too
likely that a controller will send a barrier before it's finished pushing
tables.

hitless restart

---

modules/OVSDriver/module/src/vport.c

It's possible for the link-add Netlink message to arrive after the openvswitch 
vport-add Netlink message, and to carry a status change such as link-up. The 
previous code would have dropped this message and never seen a link-up 
notification for that port.

OVSDriver: handle link status changes for new/delete also

---

modules/OVSDriver/module/src/util.c

OVSDriver: fix crash with empty nl_recv

---

modules/OVSDriver/module/src/ovs_driver_int.h
modules/OVSDriver/module/src/util.c
modules/OVSDriver/module/src/vport.c

Unlike LRO, GRO should be safe to enable when bridging.

OVSDriver: enable GRO on uplinks
