floodlight/ivs

build/setup.sh

setup.sh: install pkg-config

---

modules/action/module/src/action.c

action: make raw VLAN push/pop more user-friendly

---

modules/pipeline_lua/module/src/actions.lua
modules/pipeline_lua/module/src/base.lua
modules/pipeline_lua/module/src/hashtable.lua
modules/pipeline_lua/module/src/murmur.lua
modules/pipeline_lua/module/src/pipeline_lua.c

These changes improve the performance and safety of the Lua pipeline. In particular the JIT compiler behaves more predictably with these tweaks.
The LuaJIT version is bumped to 2.1 to allow us to optimize the multiply step in the hash function to use integer arithmetic.

Lua pipeline improvements

---

modules/OVSDriver/module/src/pktout.c

set skb priority for packets sent through pipeline

---

targets/ivs/tests.txt

ivs: disable a couple of OF 1.0 tests for unsupported features

---

modules/OVSDriver/module/src/vport.c

OVSDriver: revalidate kflows on link status change

---

.abat-automerge

speed up pre-checkin builds

---

modules/OVSDriver/module/src/barrier.c
modules/OVSDriver/module/src/ovs_driver_int.h
modules/OVSDriver/module/src/util.c
modules/OVSDriver/module/src/vport.c

optimize port status changes

---

.gitmodules

use git:// URL for loxigen-artifacts submodule

---

modules/action/module/inc/action/action.h
modules/action/module/src/action.c

add userspace actions

---

modules/OVSDriver/module/src/dump.c
modules/OVSDriver/module/src/kflow.c
modules/OVSDriver/module/src/pktout.c
modules/OVSDriver/module/src/translate_match.c
modules/OVSDriver/module/src/upcall.c
modules/action/module/inc/action/action.h
modules/action/module/src/action.c
modules/pipeline_standard/module/src/cfr.h
modules/pipeline_standard/module/src/pipeline_standard.c
modules/tcam/module/inc/tcam/tcam.h
modules/tcam/module/src/tcam.c
modules/tcam/utest/main.c

megaflow implementation for pipeline_standard

---

modules/OVSDriver/module/src/vport.c

add bsn_uplink port desc property, and fix a port desc bug

---

README.md
build/build-debian-packages-inner.sh
build/build-debian-packages.sh
build/build-rhel-packages.sh
build/setup.sh
debian/rules
docker/ubuntu14.04/Dockerfile
modules/OVSDriver/module/src/translate_match.c
modules/OVSDriver/module/src/upcall.c
modules/action/module/src/action.c
modules/l2table/module/src/l2table.c
modules/pipeline_standard/module/src/action.c
modules/pipeline_standard/module/src/cfr.c
modules/tcam/module/src/tcam.c
rhel/ivs-7.0.spec

build Ubuntu 14.04 packages using Docker, and other build system improvements

---

targets/ivs-ctl/main.c

ivs-ctl: add list-ports command

---

modules/OVSDriver/module/src/ovs_driver.c

OVSDriver: improve DPID generation

---

modules/OVSDriver/module/src/ovs_driver.c

OVSDriver: move datapath name hash to upper bytes of dpid

---

build/build-debian-packages.sh
build/build-rhel-packages.sh

set BUILD_ID when building packages using Docker

---

modules/OVSDriver/module/src/barrier.c
modules/OVSDriver/module/src/kflow.c
modules/OVSDriver/module/src/multicast.c
modules/OVSDriver/module/src/ovs_driver_int.h
modules/OVSDriver/module/src/pktin.c
modules/OVSDriver/module/src/pktout.c
modules/OVSDriver/module/src/upcall.c
modules/OVSDriver/module/src/util.c
modules/OVSDriver/module/src/vport.c

Most of OVSDriver was written long before I created the debug counters module, 
so coverage was pretty bad. These changes add debug counters to the
interesting codepaths I found.

OVSDriver: add debug counters

---

README.md

README: add build dependencies for CentOS 7

---

targets/ivs/main.c

ivs: continue startup after failing to add a port

---

build/oftest.py

This can be picked up by Jenkins.

oftest.py: support writing a JUnit test results file

---

modules/OVSDriver/module/src/upcall.c

OVSDriver: remove redundant error log

---

modules/pipeline/module/src/pipeline.c

Found by the builtin kflow mask test. If inband management is enabled we have 
to match on the in_port and possibly the VLAN. The rule is we should set the 
corresponding bits in the mask before using the field.

pipeline: fix a megaflow mask issue for inband management

---

modules/OVSDriver/module/src/ovs_driver_int.h
modules/OVSDriver/module/src/pktin.c
modules/OVSDriver/module/src/vport.c
modules/action/module/inc/action/action.h
modules/action/module/src/action.c
modules/ivs/module/inc/ivs/ivs.h

OVSDriver: Deprecate per port pktin socket and related api's

---

modules/OVSDriver/module/src/upcall.c

Upcall processes use prctl(PR_SET_PDEATHSIG) to be notified when the main 
process dies. There's a short window where the child process has started but 
not yet run prctl. If the parent dies during this window the child won't 
notice. I've seen this race occur when there's a crash during startup.

OVSDriver: fix parent death race

---

modules/packet_trace/module/src/packet_trace.c
targets/ivs-ctl/main.c

packet trace improvements

---

modules/OVSDriver/module/src/util.c
modules/OVSDriver/module/src/vport.c

OVSDriver: ask kernel to allocate netlink PIDs

---

targets/ivs/main.c

crash handler improvements

---

modules/OVSDriver/module/src/multicast.c
modules/OVSDriver/module/src/pktin_socket.c
modules/OVSDriver/module/src/util.c
modules/OVSDriver/module/src/vport.c
modules/ivs/module/inc/ivs/ivs.h

OVSDriver: read multiple multicast messages per trip through the event loop

---

modules/OVSDriver/module/src/kflow.c
modules/OVSDriver/module/src/util.c
targets/ivs/main.c

fix a use after free error

---

modules/OVSDriver/module/src/upcall.c
targets/ivs/Makefile

drop privileges and de-nice upcall threads

---

debian/control
docker/centos7/Dockerfile
docker/ubuntu14.04/Dockerfile
rhel/ivs-7.0.spec

add dependencies on libcap

---

README.md

add libcap dependencies to README

---

modules/OVSDriver/module/src/upcall.c

restart upcall processes on termination

---

modules/OVSDriver/module/src/kflow.c

move kflow expiration to a long running task

---

modules/pipeline_lua/module/src/pipeline_lua.c
oftests/lua/command.lua
oftests/lua/hashtable_benchmark.lua
oftests/lua/hashtable_test.lua
oftests/lua/l2switch.lua
oftests/lua/tables.lua
oftests/lua_basic.py
oftests/lua_common.py
oftests/lua_l2switch.py

These had been sitting in my tree for a while. We'll expand l2switch and its tests as we add more features to pipeline_lua.

Lua pipeline OFTests

---

modules/pipeline_lua/module/src/base.lua
modules/pipeline_lua/module/src/pipeline_lua.c
oftests/l2switch.x
oftests/l2switch_xdr.py
oftests/lua/l2switch.lua
oftests/lua/l2switch_xdr.lua
oftests/lua_l2switch.py

use generated XDR code in Lua tests

---

modules/OVSDriver/module/src/vport.c

add queue stats functionality

---

modules/OVSDriver/module/src/vport.c
modules/ivs/module/inc/ivs/ivs.h

OVSDriver: add rx_bad_vlan extended port stats

---

modules/pipeline_lua/module/src/base.lua
modules/pipeline_lua/module/src/log.c
modules/pipeline_lua/module/src/pipeline_lua.c
modules/pipeline_lua/module/src/pipeline_lua_int.h
modules/pipeline_lua/module/src/stats.c
modules/pipeline_lua/module/src/table.c
modules/stats/module/inc/stats/stats.h
modules/stats/module/src/stats.c
oftests/l2switch.x
oftests/l2switch_xdr.py
oftests/lua/l2switch.lua
oftests/lua/l2switch_xdr.lua
oftests/lua_l2switch.py
targets/ivs/Makefile

These changes expose more features to the Lua pipeline that are already available for C pipelines.

pipeline_lua: cookies, logging, and stats

---

modules/pipeline_lua/module/src/actions.lua
modules/pipeline_lua/module/src/pipeline_lua.c
oftests/lua/l2switch.lua
oftests/lua_l2switch.py

lua pktin socket

---

modules/pipeline_lua/module/src/base.lua
modules/pipeline_lua/module/src/pipeline_lua.c
oftests/lua/pktin.lua
oftests/lua_l2switch.py

lua pktin processing 

---

modules/OVSDriver/module/src/upcall.c

PR_SET_DEATHSIG asks the kernel to send an upcall process a SIGKILL when the 
parent process dies, but if the parent has already died when we do the prctl 
then no signal will be sent. I previously tried to work around this with 
kill(parent, 0), which would return ESRCH if the parent had already died. It 
turns out this is insufficient because kill returns success if the target is a 
zombie.
This change uses the traditional method of watching for the other side of a 
pipe to close.

OVSDriver: fix a zombie parent death race

---

targets/ivs/main.c

ivs: support IPv6 controllers on the commandline

---

modules/OVSDriver/module/src/multicast.c

Reusing the multicast socket led to a situation where nl_recvmsgs_default
would get ENOBUFS from the kernel because multicast messages were coming in at
the same time as the dump. This change fixes reusing a kernel datapath with
more than a couple hundred ports.

OVSDriver: create a new socket to receive vport dumps

---

targets/ivs/Makefile
targets/ivs/tests.txt

ivs: switch to OFConnectionManager2

---

targets/ivs/main.c

We saw an issue where users would run ivs without any arguments when they 
probably intended to run "ivs --help". The new ivs would steal the ports from 
the old one, which would remain running. This is turning out to be a common 
mistake so I've added a pidfile to prevent multiple ivs running at once (for 
the same kernel datapath).

ivs: use a pidfile

---

docker/centos7/Dockerfile
docker/ubuntu14.04/Dockerfile

docker: add libpcap-dev packages

---

targets/ivs/main.c

add more useful information to the OpenFlow desc stats message

---

targets/ivs/main.c

ivs: listen for OpenFlow on a unix domain socket

---

targets/ivs/tests-1.3.txt
targets/ivs/tests.txt

We want Jenkins to reject any pull requests that cause new test failures.

blacklist a few tests

---

modules/OVSDriver/module/src/util.c

libnl 3.2.25 broke our method of using the kernel to allocate Netlink ports. 
However, in the process it also fixed the underlying issue that necessitated 
that hack. This change detects whether we have a newer version of libnl and 
uses its port allocation scheme.
The nl_has_capability function is not defined for earlier versions of libnl,
so we declare it as a weak symbol and check at runtime whether it exists.

OVSDriver: use libnl port allocation when possible

---

modules/ivs/module/inc/ivs/ivs.h
targets/ivs/main.c

ivs: add globals for version number, build ID, etc

---

modules/OVSDriver/module/src/hitless.c

OVSDriver: squelch repeated bsn_takeover message logs

---

modules/OVSDriver/module/src/vport.c

vport reliability improvements

---

targets/ivs-ctl/main.c

ivs-ctl: send "show" output to stdout

---

modules/OVSDriver/module/src/vport.c

`nl_cache_refill` does not execute the callbacks registered with
`nl_cache_mngr_add`. If a port status change was picked up by a refill then
the link change callback would never get called.

OVSDriver: use a separate link cache for stats

---

modules/OVSDriver/module/src/vport.c

OVSDriver: fix port number for OVSP_LOCAL in indigo_port_interface_list

---

modules/OVSDriver/module/src/ovs_driver_int.h
modules/OVSDriver/module/src/vport.c

OVSDriver: support link up/down extended port stats
